-- ============================================================
-- V1__init.sql  –  Schema + Seed data
-- Passwords V2: password (bcrypt)
-- Passwords V4: nombre123 (bcrypt strength 10)
-- ============================================================

-- ============================================================
-- SCHEMA
-- ============================================================

create table categorias (
    activo boolean not null,
    categoria_id bigint generated by default as identity,
    fecha_creacion timestamp(6) not null,
    negocio_id bigint not null,
    descripcion varchar(100) not null,
    primary key (categoria_id),
    unique (descripcion, negocio_id)
);

create table clientes (
    activo boolean not null,
    cliente_id bigint generated by default as identity,
    fecha_creacion timestamp(6) not null,
    negocio_id bigint not null,
    telefono varchar(20),
    nombre_completo varchar(100) not null,
    primary key (cliente_id)
);

create table compras (
    recibida boolean not null,
    compra_id bigint generated by default as identity,
    fecha_carga timestamp(6) not null,
    fecha_recepcion timestamp(6),
    negocio_id bigint not null,
    usuario_id bigint not null,
    primary key (compra_id)
);

create table formas_pago (
    forma_id bigint generated by default as identity,
    descripcion varchar(100) not null unique,
    primary key (forma_id)
);

create table items_compras (
    cantidad integer not null,
    compra_id bigint not null,
    item_compra_id bigint generated by default as identity,
    precio_id bigint not null,
    producto_id bigint not null,
    primary key (item_compra_id)
);

create table items_ventas (
    cantidad integer not null,
    item_venta_id bigint generated by default as identity,
    precio_id bigint not null,
    producto_id bigint not null,
    venta_id bigint not null,
    primary key (item_venta_id)
);

create table negocios (
    activo boolean not null,
    fecha_creacion timestamp(6),
    negocio_id bigint generated by default as identity,
    parametro_id bigint unique,
    nombre_negocio varchar(100) not null unique,
    primary key (negocio_id)
);

create table parametros (
    parametro_id bigint generated by default as identity,
    una_compra_distintos_proveedores boolean not null,
    exigir_forma_de_pago_al_cargar_venta boolean not null,
    exigir_cliente_al_cargar_venta boolean not null,
    permitir_vender_sin_stock boolean not null,
    empleado_puede_cargar_compras boolean not null,
    empleado_puede_utilizar_abm boolean not null,
    primary key (parametro_id)
);

create table precios (
    monto numeric(38,2) not null,
    desde timestamp(6) not null,
    hasta timestamp(6),
    precio_id bigint generated by default as identity,
    producto_id bigint not null,
    tipo varchar(255) not null check ((tipo in ('COMPRA','VENTA'))),
    primary key (precio_id)
);

create table subcategorias (
    activo boolean not null,
    subcategoria_id bigint generated by default as identity,
    fecha_creacion timestamp(6) not null,
    categoria_id bigint not null,
    descripcion varchar(100) not null,
    primary key (subcategoria_id),
    unique (descripcion, categoria_id)
);

create table productos (
    activo boolean not null,
    stock integer not null,
    categoria_id bigint,
    fecha_creacion timestamp(6) not null,
    negocio_id bigint not null,
    producto_id bigint generated by default as identity,
    proveedor_id bigint,
    subcategoria_id bigint,
    descripcion varchar(100) not null,
    primary key (producto_id),
    unique (descripcion, negocio_id)
);

create table proveedores (
    activo boolean not null,
    negocio_id bigint not null,
    proveedor_id bigint generated by default as identity,
    telefono varchar(20),
    descripcion varchar(100) not null,
    primary key (proveedor_id)
);

create table usuarios (
    activo boolean not null,
    fecha_creacion timestamp(6) not null,
    negocio_id bigint not null,
    ultimo_acceso timestamp(6),
    usuario_id bigint generated by default as identity,
    nombre_completo varchar(100),
    email varchar(255) not null,
    password varchar(255) not null,
    rol varchar(255) not null check ((rol in ('SUPERADMIN','ADMIN','GERENTE','EMPLEADO'))),
    primary key (usuario_id)
);

create table ventas (
    cliente_id bigint not null,
    fecha_hora timestamp(6) not null,
    forma_id bigint,
    negocio_id bigint not null,
    usuario_id bigint not null,
    venta_id bigint generated by default as identity,
    primary key (venta_id)
);

alter table if exists categorias
    add constraint FK3wmdhk8dknu188g5rugb6rho5
    foreign key (negocio_id)
    references negocios;

alter table if exists clientes
    add constraint FKccuovxxyru49puoyq0hgqb0s5
    foreign key (negocio_id)
    references negocios;

alter table if exists compras
    add constraint FK4lnkw9964v2gf3b2sjbaealqw
    foreign key (usuario_id)
    references usuarios;

alter table if exists compras
    add constraint FKe9smdxck4xoh1v1m0goyw4ssx
    foreign key (negocio_id)
    references negocios;

alter table if exists items_compras
    add constraint FK7p988crripxo0s3lil49h3iqw
    foreign key (compra_id)
    references compras;

alter table if exists items_compras
    add constraint FKtqakqr5qpsi4l38mj1wvscuvw
    foreign key (precio_id)
    references precios;

alter table if exists items_compras
    add constraint FK2i896qk0nuu90kncjd7fagcll
    foreign key (producto_id)
    references productos;

alter table if exists items_ventas
    add constraint FKcokmp28vgx04mhilrbvvpi8vw
    foreign key (precio_id)
    references precios;

alter table if exists items_ventas
    add constraint FKk08c458e2s7spce343h261c1g
    foreign key (producto_id)
    references productos;

alter table if exists items_ventas
    add constraint FKf5m002pvtkrx9skl7emqhkca
    foreign key (venta_id)
    references ventas;

alter table if exists negocios
    add constraint FKcofy3vap8rn38cod9fox97bmc
    foreign key (parametro_id)
    references parametros;

alter table if exists precios
    add constraint FKe1biuxdgj99ycn40dx91xa32v
    foreign key (producto_id)
    references productos;

alter table if exists productos
    add constraint FK2fwq10nwymfv7fumctxt9vpgb
    foreign key (categoria_id)
    references categorias;

alter table if exists productos
    add constraint FKd2djtywmbw974dw5hjrw5ugbh
    foreign key (negocio_id)
    references negocios;

alter table if exists productos
    add constraint FK4s80lxlx2fkci25fcx4r0nbex
    foreign key (proveedor_id)
    references proveedores;

alter table if exists productos
    add constraint fk_productos_subcategorias
    foreign key (subcategoria_id)
    references subcategorias;

alter table if exists proveedores
    add constraint FK5kiu3tglvogheiidk5ddnupk0
    foreign key (negocio_id)
    references negocios;

alter table if exists subcategorias
    add constraint fk_subcategorias_categorias
    foreign key (categoria_id)
    references categorias;

alter table if exists usuarios
    add constraint FK4te6rxo55nnja1re00108m8pj
    foreign key (negocio_id)
    references negocios;

alter table if exists ventas
    add constraint FK4dgjhccl2uuo8swmxlxb4ipb5
    foreign key (cliente_id)
    references clientes;

alter table if exists ventas
    add constraint FK3t65vghi4lk9wacxgjg56tjed
    foreign key (forma_id)
    references formas_pago;

alter table if exists ventas
    add constraint FKnvexb891pwiptc9p3534stpml
    foreign key (negocio_id)
    references negocios;

alter table if exists ventas
    add constraint FKco9r9xjcdqtgd4nvnnolsr6ei
    foreign key (usuario_id)
    references usuarios;

-- ============================================================
-- SEED DATA
-- ============================================================

-- ------------------------------------------------------------
-- FORMAS DE PAGO
-- ------------------------------------------------------------

INSERT INTO formas_pago (descripcion) VALUES
    ('Efectivo'),
    ('Tarjeta de débito'),
    ('Tarjeta de crédito'),
    ('Transferencia bancaria'),
    ('Mercado Pago');

-- ------------------------------------------------------------
-- NEGOCIOS BASE (con sus parámetros, usuarios, proveedores,
-- categorías, productos iniciales, precios, clientes,
-- compras y ventas de ejemplo)
-- ------------------------------------------------------------

WITH param1 AS (
    INSERT INTO parametros (
        una_compra_distintos_proveedores,
        exigir_forma_de_pago_al_cargar_venta,
        exigir_cliente_al_cargar_venta,
        permitir_vender_sin_stock,
        empleado_puede_cargar_compras,
        empleado_puede_utilizar_abm
    )
    VALUES (false, true, false, false, false, false)
    RETURNING parametro_id
),

param2 AS (
    INSERT INTO parametros (
        una_compra_distintos_proveedores,
        exigir_forma_de_pago_al_cargar_venta,
        exigir_cliente_al_cargar_venta,
        permitir_vender_sin_stock,
        empleado_puede_cargar_compras,
        empleado_puede_utilizar_abm
    )
    VALUES (true, false, false, false, false, false)
    RETURNING parametro_id
),

negocio1 AS (
    INSERT INTO negocios (nombre_negocio, fecha_creacion, activo, parametro_id)
    SELECT 'Ferretería El Tornillo', '2023-01-15', true, parametro_id
    FROM param1
    RETURNING negocio_id
),

negocio2 AS (
    INSERT INTO negocios (nombre_negocio, fecha_creacion, activo, parametro_id)
    SELECT 'Librería El Saber', '2023-03-20', true, parametro_id
    FROM param2
    RETURNING negocio_id
),

u_admin1 AS (
    INSERT INTO usuarios (email, nombre_completo, password, ultimo_acceso, fecha_creacion, activo, rol, negocio_id)
    SELECT 'admin@ferreteria.com', 'Carlos Gómez',
           '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
           NOW(), '2023-01-15', true, 'ADMIN', negocio_id
    FROM negocio1
    RETURNING usuario_id
),

u_empleado1 AS (
    INSERT INTO usuarios (email, nombre_completo, password, ultimo_acceso, fecha_creacion, activo, rol, negocio_id)
    SELECT 'empleado@ferreteria.com', 'Marcos Rodríguez',
           '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
           NOW(), '2023-01-20', true, 'EMPLEADO', negocio_id
    FROM negocio1
    RETURNING usuario_id
),

u_admin2 AS (
    INSERT INTO usuarios (email, nombre_completo, password, ultimo_acceso, fecha_creacion, activo, rol, negocio_id)
    SELECT 'admin@libreria.com', 'Sofía Herrera',
           '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
           NOW(), '2023-03-20', true, 'ADMIN', negocio_id
    FROM negocio2
    RETURNING usuario_id
),

prov1 AS (
    INSERT INTO proveedores (descripcion, telefono, activo, negocio_id)
    SELECT 'Distribuidora MetalMax', '2214-1111', true, negocio_id
    FROM negocio1
    RETURNING proveedor_id
),

prov2 AS (
    INSERT INTO proveedores (descripcion, telefono, activo, negocio_id)
    SELECT 'Editorial Norma', '1145-4444', true, negocio_id
    FROM negocio2
    RETURNING proveedor_id
),

cat1 AS (
    INSERT INTO categorias (descripcion, fecha_creacion, activo, negocio_id)
    SELECT 'Herramientas', '2023-01-15', true, negocio_id
    FROM negocio1
    RETURNING categoria_id
),

cat2 AS (
    INSERT INTO categorias (descripcion, fecha_creacion, activo, negocio_id)
    SELECT 'Libros', '2023-03-20', true, negocio_id
    FROM negocio2
    RETURNING categoria_id
),

prod1 AS (
    INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, proveedor_id, negocio_id)
    SELECT 'Martillo 500g', 20, '2023-01-20', true,
           cat1.categoria_id, prov1.proveedor_id, negocio1.negocio_id
    FROM cat1, prov1, negocio1
    RETURNING producto_id
),

prod2 AS (
    INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, proveedor_id, negocio_id)
    SELECT 'El Principito', 30, '2023-03-25', true,
           cat2.categoria_id, prov2.proveedor_id, negocio2.negocio_id
    FROM cat2, prov2, negocio2
    RETURNING producto_id
),

precio1_compra AS (
    INSERT INTO precios (monto, desde, hasta, tipo, producto_id)
    SELECT 1500.00, '2023-01-20', NULL, 'COMPRA', producto_id
    FROM prod1
    RETURNING precio_id
),

precio1_venta AS (
    INSERT INTO precios (monto, desde, hasta, tipo, producto_id)
    SELECT 2200.00, '2023-01-20', NULL, 'VENTA', producto_id
    FROM prod1
    RETURNING precio_id
),

precio2_compra AS (
    INSERT INTO precios (monto, desde, hasta, tipo, producto_id)
    SELECT 1800.00, '2023-03-25', NULL, 'COMPRA', producto_id
    FROM prod2
    RETURNING precio_id
),

precio2_venta AS (
    INSERT INTO precios (monto, desde, hasta, tipo, producto_id)
    SELECT 2800.00, '2023-03-25', NULL, 'VENTA', producto_id
    FROM prod2
    RETURNING precio_id
),

cliente1 AS (
    INSERT INTO clientes (nombre_completo, telefono, fecha_creacion, activo, negocio_id)
    SELECT 'Roberto Sánchez', '2214-9001', '2023-01-25', true, negocio_id
    FROM negocio1
    RETURNING cliente_id
),

cliente2 AS (
    INSERT INTO clientes (nombre_completo, telefono, fecha_creacion, activo, negocio_id)
    SELECT 'Martina Ruiz', '1145-8001', '2023-03-28', true, negocio_id
    FROM negocio2
    RETURNING cliente_id
),

compra1 AS (
    INSERT INTO compras (recibida, fecha_carga, fecha_recepcion, usuario_id, negocio_id)
    SELECT true, '2024-01-10 09:00:00', '2024-01-11 12:00:00',
           u_admin1.usuario_id, negocio1.negocio_id
    FROM u_admin1, negocio1
    RETURNING compra_id
),

compra2 AS (
    INSERT INTO compras (recibida, fecha_carga, fecha_recepcion, usuario_id, negocio_id)
    SELECT true, '2024-02-05 10:00:00', '2024-02-06 13:00:00',
           u_admin2.usuario_id, negocio2.negocio_id
    FROM u_admin2, negocio2
    RETURNING compra_id
),

ic1 AS (
    INSERT INTO items_compras (cantidad, precio_id, producto_id, compra_id)
    SELECT 10, precio1_compra.precio_id, prod1.producto_id, compra1.compra_id
    FROM precio1_compra, prod1, compra1
    RETURNING item_compra_id
),

ic2 AS (
    INSERT INTO items_compras (cantidad, precio_id, producto_id, compra_id)
    SELECT 20, precio2_compra.precio_id, prod2.producto_id, compra2.compra_id
    FROM precio2_compra, prod2, compra2
    RETURNING item_compra_id
),

venta1 AS (
    INSERT INTO ventas (fecha_hora, cliente_id, forma_id, usuario_id, negocio_id)
    SELECT '2024-01-15 10:30:00', cliente1.cliente_id,
           (SELECT forma_id FROM formas_pago WHERE descripcion = 'Efectivo'),
           u_empleado1.usuario_id, negocio1.negocio_id
    FROM cliente1, u_empleado1, negocio1
    RETURNING venta_id
),

venta2 AS (
    INSERT INTO ventas (fecha_hora, cliente_id, forma_id, usuario_id, negocio_id)
    SELECT '2024-03-10 11:00:00', cliente2.cliente_id,
           (SELECT forma_id FROM formas_pago WHERE descripcion = 'Mercado Pago'),
           u_admin2.usuario_id, negocio2.negocio_id
    FROM cliente2, u_admin2, negocio2
    RETURNING venta_id
),

iv1 AS (
    INSERT INTO items_ventas (cantidad, precio_id, producto_id, venta_id)
    SELECT 2, precio1_venta.precio_id, prod1.producto_id, venta1.venta_id
    FROM precio1_venta, prod1, venta1
    RETURNING item_venta_id
),

iv2 AS (
    INSERT INTO items_ventas (cantidad, precio_id, producto_id, venta_id)
    SELECT 1, precio2_venta.precio_id, prod2.producto_id, venta2.venta_id
    FROM precio2_venta, prod2, venta2
    RETURNING item_venta_id
)

SELECT 'Datos base insertados' AS resultado;

-- ------------------------------------------------------------
-- USUARIOS ADICIONALES
-- ------------------------------------------------------------

INSERT INTO usuarios (email, nombre_completo, password, ultimo_acceso, fecha_creacion, activo, rol, negocio_id)
SELECT v.email, v.nombre, v.pwd, NOW(), v.fecha::timestamp, v.act, v.rol, n.negocio_id
FROM (VALUES
    ('laura@ferreteria.com',   'Laura González',  '$2b$10$7YLYCFpkPLYctO519OAopOmffg2UCItWxPVwF3G7XGkoKpfFiWpie', '2023-02-01', true,  'GERENTE'),
    ('diego@ferreteria.com',   'Diego Martínez',  '$2b$10$KkVFDkbX/Ck85rife4jnRO2/lIP/G2YNWzor.DdqylqhQUCHyYvfK', '2023-02-10', true,  'EMPLEADO'),
    ('ana@ferreteria.com',     'Ana Soria',       '$2b$10$SWFpPvHhn0DrRMJdMse9AO0Bug9jLBwB1Bd2Whr1dzHGAgZCeUujm',  '2023-03-05', true,  'EMPLEADO'),
    ('valeria@ferreteria.com', 'Valeria Ruiz',    '$2b$10$zYg9nhXIhRKnne9Urf8nAuivhzs8OZcxB5cxvmKDYmzzf5G2gDQVe', '2023-04-01', true,  'GERENTE'),
    ('oscar@ferreteria.com',   'Oscar Fernández', '$2b$10$NO9k2OL2ekOaYsI/TC.3S.YsVvHgwwgcntICXP3bSLX1KqLVTO8SW', '2023-04-15', false, 'EMPLEADO')
) AS v(email, nombre, pwd, fecha, act, rol)
JOIN negocios n ON n.nombre_negocio = 'Ferretería El Tornillo';

INSERT INTO usuarios (email, nombre_completo, password, ultimo_acceso, fecha_creacion, activo, rol, negocio_id)
SELECT v.email, v.nombre, v.pwd, NOW(), v.fecha::timestamp, v.act, v.rol, n.negocio_id
FROM (VALUES
    ('pedro@libreria.com',   'Pedro Ramírez',   '$2b$10$.4VyzQXdyjBPHmhku2DodOY6vV/GAI7dXa6tkLMxbSE4EWIwoXMja', '2023-04-01', true,  'GERENTE'),
    ('lucia@libreria.com',   'Lucía Vega',      '$2b$10$JtKQR6HYO1NbG6Pt1V3Kve7scELyp8jRpEeR5bpXmreJZXWSkbEuG',  '2023-04-10', true,  'EMPLEADO'),
    ('miguel@libreria.com',  'Miguel Torres',   '$2b$10$fh8g4.7rGKM/yGvRN5iqd.bvKcvxrM76Z9KT68kQTfGkQdFQtsZiq',  '2023-05-01', true,  'EMPLEADO'),
    ('gabriel@libreria.com', 'Gabriel Moreno',  '$2b$10$BUes35u6ZusRR8ybD.sl4eDZ1iIBTt4Rb3h6AmkMZSsIwU9PDJBU.',  '2023-05-15', true,  'GERENTE'),
    ('beatriz@libreria.com', 'Beatriz Salinas', '$2b$10$LZ/YiWWuKlOB/vD3oxa84uZqV0r/n.sBG.GdkQTKz3tJKomDuZr1S',  '2023-06-01', false, 'EMPLEADO')
) AS v(email, nombre, pwd, fecha, act, rol)
JOIN negocios n ON n.nombre_negocio = 'Librería El Saber';

-- ------------------------------------------------------------
-- PROVEEDORES ADICIONALES
-- ------------------------------------------------------------

INSERT INTO proveedores (descripcion, telefono, activo, negocio_id)
SELECT v.descripcion, v.tel, true, n.negocio_id
FROM (VALUES
    ('Importadora TechTools',         '2214-5555'),
    ('Ferretería Mayorista Sur',      '2214-6666'),
    ('Distribuidora Eléctrica Norte', '2214-7777')
) AS v(descripcion, tel)
JOIN negocios n ON n.nombre_negocio = 'Ferretería El Tornillo';

INSERT INTO proveedores (descripcion, telefono, activo, negocio_id)
SELECT v.descripcion, v.tel, true, n.negocio_id
FROM (VALUES
    ('Editorial Santillana',  '1145-2222'),
    ('Distribuidora del Sur', '1145-3333'),
    ('Editorial Planeta',     '1145-4455')
) AS v(descripcion, tel)
JOIN negocios n ON n.nombre_negocio = 'Librería El Saber';

-- ------------------------------------------------------------
-- CATEGORÍAS ADICIONALES
-- ------------------------------------------------------------

INSERT INTO categorias (descripcion, fecha_creacion, activo, negocio_id)
SELECT v.descripcion, '2023-01-15'::timestamp, v.act, n.negocio_id
FROM (VALUES
    ('Herramientas Eléctricas',   true),
    ('Fijaciones y Tornillería',  true),
    ('Pinturas y Accesorios',     true),
    ('Plomería',                  true),
    ('Electricidad',              true),
    ('Construcción',              true),
    ('Jardín',                    true),
    ('Seguridad',                 true),
    ('Adhesivos y Selladores',    true),
    ('Iluminación',               true),
    ('Cerrajería',                true),
    ('Abrasivos',                 true),
    ('Mantenimiento',             false)
) AS v(descripcion, act)
JOIN negocios n ON n.nombre_negocio = 'Ferretería El Tornillo';

INSERT INTO categorias (descripcion, fecha_creacion, activo, negocio_id)
SELECT v.descripcion, '2023-03-20'::timestamp, true, n.negocio_id
FROM (VALUES
    ('Papelería'),
    ('Útiles Escolares'),
    ('Arte y Manualidades'),
    ('Tecnología'),
    ('Juguetería Educativa'),
    ('Cuadernos y Blocks'),
    ('Escritura')
) AS v(descripcion)
JOIN negocios n ON n.nombre_negocio = 'Librería El Saber';

-- ------------------------------------------------------------
-- SUBCATEGORÍAS
-- ------------------------------------------------------------

INSERT INTO subcategorias (descripcion, fecha_creacion, activo, categoria_id)
SELECT v.descripcion, '2023-01-15'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c
        JOIN negocios n ON n.negocio_id = c.negocio_id
        WHERE c.descripcion = v.cat AND n.nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Manuales',   'Herramientas'),
    ('Medición',   'Herramientas'),
    ('Taladros',   'Herramientas Eléctricas'),
    ('Amoladoras', 'Herramientas Eléctricas'),
    ('Sierras',    'Herramientas Eléctricas'),
    ('Tornillos',  'Fijaciones y Tornillería'),
    ('Bulones',    'Fijaciones y Tornillería'),
    ('Clavos',     'Fijaciones y Tornillería'),
    ('Tarugos',    'Fijaciones y Tornillería'),
    ('Látex',      'Pinturas y Accesorios'),
    ('Esmalte',    'Pinturas y Accesorios'),
    ('Barniz',     'Pinturas y Accesorios')
) AS v(descripcion, cat);

INSERT INTO subcategorias (descripcion, fecha_creacion, activo, categoria_id)
SELECT v.descripcion, '2023-03-20'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c
        JOIN negocios n ON n.negocio_id = c.negocio_id
        WHERE c.descripcion = v.cat AND n.nombre_negocio = 'Librería El Saber')
FROM (VALUES
    ('Infantil',              'Libros'),
    ('Juvenil',               'Libros'),
    ('Adultos',               'Libros'),
    ('Técnicos y Académicos', 'Libros'),
    ('Pintura',               'Arte y Manualidades'),
    ('Modelado',              'Arte y Manualidades'),
    ('Escolares',             'Cuadernos y Blocks'),
    ('Profesionales',         'Cuadernos y Blocks'),
    ('Lapiceras',             'Escritura'),
    ('Marcadores',            'Escritura'),
    ('Lápices',               'Escritura')
) AS v(descripcion, cat);

-- ------------------------------------------------------------
-- PRODUCTOS — FERRETERÍA EL TORNILLO
-- ------------------------------------------------------------

-- Herramientas / Manuales / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Herramientas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Manuales' AND c.descripcion = 'Herramientas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Destornillador plano 6x150',   50),
    ('Destornillador Phillips N2',   50),
    ('Llave inglesa 12 pulgadas',    30),
    ('Alicate universal 8 pulgadas', 40),
    ('Pinza de corte 7 pulgadas',    35),
    ('Nivel de burbuja 60cm',        20),
    ('Cutter profesional 18mm',      45)
) AS v(descripcion, stock);

-- Herramientas / Medición / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Herramientas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Medición' AND c.descripcion = 'Herramientas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Metro retráctil 5m',        40),
    ('Metro retráctil 3m',        50),
    ('Escuadra carpintero 30cm',  30)
) AS v(descripcion, stock);

-- Herramientas / Medición / TechTools
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Herramientas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Medición' AND c.descripcion = 'Herramientas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Importadora TechTools' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Nivel digital',          15),
    ('Calibre Vernier 150mm',  10)
) AS v(descripcion, stock);

-- Herramientas Eléctricas / Taladros / TechTools
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Herramientas Eléctricas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Taladros' AND c.descripcion = 'Herramientas Eléctricas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Importadora TechTools' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Taladro 500W',               20),
    ('Taladro 750W',               15),
    ('Taladro percutor 800W',      10),
    ('Atornillador a batería 12V', 12),
    ('Taladro de banco 350W',       5)
) AS v(descripcion, stock);

-- Herramientas Eléctricas / Amoladoras / TechTools
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Herramientas Eléctricas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Amoladoras' AND c.descripcion = 'Herramientas Eléctricas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Importadora TechTools' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Amoladora 115mm 720W',   15),
    ('Amoladora 180mm 1400W',  10),
    ('Amoladora 230mm 2000W',   8)
) AS v(descripcion, stock);

-- Herramientas Eléctricas / Sierras / TechTools
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Herramientas Eléctricas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Sierras' AND c.descripcion = 'Herramientas Eléctricas' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Importadora TechTools' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Sierra circular 185mm', 8),
    ('Sierra caladora 650W',  10),
    ('Sierra sable 900W',      5)
) AS v(descripcion, stock);

-- Fijaciones / Tornillos / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Fijaciones y Tornillería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Tornillos' AND c.descripcion = 'Fijaciones y Tornillería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Tornillo madera 3x30 x100u',        100),
    ('Tornillo madera 4x40 x100u',         80),
    ('Tornillo autoperforante 4x25 x100u', 90),
    ('Tornillo madera 5x50 x50u',          70),
    ('Tornillo Spax 6x60 x50u',            60)
) AS v(descripcion, stock);

-- Fijaciones / Bulones / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Fijaciones y Tornillería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Bulones' AND c.descripcion = 'Fijaciones y Tornillería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Bulón hexagonal M8x50',    60),
    ('Bulón hexagonal M10x70',   50),
    ('Tuerca hexagonal M8 x50u', 80)
) AS v(descripcion, stock);

-- Fijaciones / Clavos / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Fijaciones y Tornillería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Clavos' AND c.descripcion = 'Fijaciones y Tornillería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Clavo de acero 50mm x1kg',      50),
    ('Clavo de acero 80mm x1kg',      40),
    ('Clavo canaleta x1kg',           35),
    ('Clavo para hormigón 50mm x1kg', 30)
) AS v(descripcion, stock);

-- Fijaciones / Tarugos / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Fijaciones y Tornillería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Tarugos' AND c.descripcion = 'Fijaciones y Tornillería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Tarugo Fischer 6mm x50u',  80),
    ('Tarugo Fischer 8mm x50u',  70),
    ('Tarugo Fischer 10mm x25u', 60)
) AS v(descripcion, stock);

-- Pinturas / Látex / Mayorista Sur
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Pinturas y Accesorios' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Látex' AND c.descripcion = 'Pinturas y Accesorios' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Ferretería Mayorista Sur' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Látex interior blanco 4L',   30),
    ('Látex interior blanco 20L',  15),
    ('Látex color 4L',             25),
    ('Látex exterior blanco 4L',   20)
) AS v(descripcion, stock);

-- Pinturas / Esmalte / Mayorista Sur
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, v.act,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Pinturas y Accesorios' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Esmalte' AND c.descripcion = 'Pinturas y Accesorios' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Ferretería Mayorista Sur' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Esmalte sintético blanco 1L', 30, true),
    ('Esmalte sintético blanco 4L', 15, true),
    ('Esmalte sintético negro 1L',  20, true),
    ('Esmalte antióxido rojo 1L',   25, true),
    ('Pintura Base Cromática 1L',    0, false)
) AS v(descripcion, stock, act);

-- Pinturas / Barniz / Mayorista Sur
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Pinturas y Accesorios' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT s.subcategoria_id FROM subcategorias s JOIN categorias c ON c.categoria_id = s.categoria_id JOIN negocios n ON n.negocio_id = c.negocio_id WHERE s.descripcion = 'Barniz' AND c.descripcion = 'Pinturas y Accesorios' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Ferretería Mayorista Sur' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Barniz marino 1L',         20),
    ('Barniz poliuretánico 1L',  15)
) AS v(descripcion, stock);

-- Plomería (sin subcategoría) / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Plomería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Caño PVC 4 pulgadas x3m',     20),
    ('Caño PVC 3 pulgadas x3m',     25),
    ('Caño PVC presión 20mm x6m',   30),
    ('Válvula esfera media pulgada', 25),
    ('Válvula esfera 3/4 pulgada',   20),
    ('Válvula compuerta media pulg', 15),
    ('Canilla jardín media pulgada', 20),
    ('Canilla cromada cocina',       15),
    ('Mezcladora baño monocomando',  10)
) AS v(descripcion, stock);

-- Electricidad (sin subcategoría) / Eléctrica Norte
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Electricidad' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora Eléctrica Norte' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Cable unipolar 2.5mm x100m',      20),
    ('Cable unipolar 4mm x100m',        15),
    ('Cable bipolar 2.5mm x100m',       18),
    ('Cable vaina plana 3x2.5mm x100m', 12),
    ('Tomacorriente bipolar 10A',        60),
    ('Tomacorriente bipolar+tierra 16A', 50),
    ('Toma exterior IP55',               30),
    ('Llave simple unipolar',            80),
    ('Llave doble unipolar',             60),
    ('Disyuntor 10A bipolar',            40)
) AS v(descripcion, stock);

-- Construcción (sin subcategoría) / Mayorista Sur
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Construcción' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Ferretería Mayorista Sur' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Cemento Portland 50kg',       30),
    ('Arena fina x25kg',            50),
    ('Cal hidratada 30kg',          40),
    ('Membrana asfáltica 4mm 10m2', 15),
    ('Sellador de grietas 1L',      30)
) AS v(descripcion, stock);

-- Jardín (sin subcategoría) / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Jardín' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Manguera reforzada 25m',       25),
    ('Aspersor giratorio',           30),
    ('Rastrillo 16 dientes',         20),
    ('Pala cuadrada con cabo',       25),
    ('Tijera de poda 8 pulgadas',    30)
) AS v(descripcion, stock);

-- Seguridad (sin subcategoría) / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Seguridad' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Casco obra blanco',              30),
    ('Guante cuero talle 10',          50),
    ('Antiparras seguridad',           40),
    ('Calzado seguridad punta acero',  20),
    ('Candado 40mm',                   35),
    ('Candado 50mm',                   25),
    ('Candado alta seguridad 60mm',    15)
) AS v(descripcion, stock);

-- Adhesivos (sin subcategoría) / Mayorista Sur
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Adhesivos y Selladores' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Ferretería Mayorista Sur' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Silicona blanca 280ml',      50),
    ('Silicona neutra 280ml',      45),
    ('Masilla epoxi bicomponente', 30),
    ('Super adhesivo 3g',          80)
) AS v(descripcion, stock);

-- Iluminación (sin subcategoría) / Eléctrica Norte
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Iluminación' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora Eléctrica Norte' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Lámpara LED 9W fría',        60),
    ('Lámpara LED 13W cálida',     55),
    ('Tira LED 5m 12V',            30),
    ('Reflector LED 20W exterior', 20)
) AS v(descripcion, stock);

-- Cerrajería (sin subcategoría) / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Cerrajería' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Cerradura embutir doble paleta', 15),
    ('Cerradura sobreponer',           20),
    ('Picaporte negro 4 pulgadas',     30),
    ('Bisagra 3 pulgadas par',         40)
) AS v(descripcion, stock);

-- Abrasivos (sin subcategoría) / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true,
       (SELECT c.categoria_id FROM categorias c JOIN negocios n ON n.negocio_id = c.negocio_id WHERE c.descripcion = 'Abrasivos' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Papel lija grano 80 x10u',   60),
    ('Papel lija grano 120 x10u',  60),
    ('Disco de corte 115mm x10u',  40),
    ('Disco desbaste 115mm x5u',   30)
) AS v(descripcion, stock);

-- Sin categoría / MetalMax
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true, NULL, NULL,
       (SELECT p.proveedor_id FROM proveedores p JOIN negocios n ON n.negocio_id = p.negocio_id WHERE p.descripcion = 'Distribuidora MetalMax' AND n.nombre_negocio = 'Ferretería El Tornillo'),
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Cinta señalizadora roja x50m', 15)
) AS v(descripcion, stock);

-- Sin categoría / sin proveedor
INSERT INTO productos (descripcion, stock, fecha_creacion, activo, categoria_id, subcategoria_id, proveedor_id, negocio_id)
SELECT v.descripcion, v.stock, '2023-06-01'::timestamp, true, NULL, NULL, NULL,
       (SELECT negocio_id FROM negocios WHERE nombre_negocio = 'Ferretería El Tornillo')
FROM (VALUES
    ('Cuaderno de obras tapa dura', 20),
    ('Marcador permanente negro',   40),
    ('Botiquín primeros auxilios',  10),
    ('Cinta de embalaje x6',        30)
) AS v(descripcion, stock);

-- ------------------------------------------------------------
-- PRECIOS (para todos los productos sin precio aún)
-- ------------------------------------------------------------

INSERT INTO precios (monto, desde, hasta, producto_id, tipo)
SELECT
    ROUND((20 + random() * 5000)::numeric, 2),
    NOW() - (random() * interval '180 days'),
    NULL,
    p.producto_id,
    'COMPRA'
FROM productos p
WHERE NOT EXISTS (
    SELECT 1 FROM precios pr
    WHERE pr.producto_id = p.producto_id AND pr.tipo = 'COMPRA'
);

INSERT INTO precios (monto, desde, hasta, producto_id, tipo)
SELECT
    ROUND((compra.monto * (1.3 + random()))::numeric, 2),
    compra.desde + interval '1 hour',
    NULL,
    compra.producto_id,
    'VENTA'
FROM (
    SELECT pr.producto_id, pr.monto, pr.desde
    FROM precios pr
    WHERE pr.tipo = 'COMPRA'
      AND NOT EXISTS (
          SELECT 1 FROM precios pv
          WHERE pv.producto_id = pr.producto_id AND pv.tipo = 'VENTA'
      )
) compra;

-- ------------------------------------------------------------
-- CLIENTES ADICIONALES
-- ------------------------------------------------------------

INSERT INTO clientes (activo, fecha_creacion, negocio_id, telefono, nombre_completo)
SELECT true, NOW() - (random() * interval '300 days'), n.negocio_id, v.telefono, v.nombre
FROM (VALUES
    ('Carlos Méndez',   '2215551001'),
    ('María López',     '2215551002'),
    ('Javier Romero',   '2215551003'),
    ('Luciana Pérez',   '2215551004'),
    ('Federico Silva',  '2215551005'),
    ('Camila Torres',   '2215551006'),
    ('Nicolás Ruiz',    '2215551007'),
    ('Valentina Sosa',  '2215551008')
) v(nombre, telefono)
JOIN negocios n ON n.nombre_negocio = 'Ferretería El Tornillo';

INSERT INTO clientes (activo, fecha_creacion, negocio_id, telefono, nombre_completo)
SELECT true, NOW() - (random() * interval '300 days'), n.negocio_id, v.telefono, v.nombre
FROM (VALUES
    ('Tomás Herrera',    '1145552001'),
    ('Julieta Castro',   '1145552002'),
    ('Agustín Medina',   '1145552003'),
    ('Florencia Vega',   '1145552004'),
    ('Martina Acosta',   '1145552005'),
    ('Bruno Navarro',    '1145552006')
) v(nombre, telefono)
JOIN negocios n ON n.nombre_negocio = 'Librería El Saber';

-- ------------------------------------------------------------
-- COMPRAS ADICIONALES
-- ------------------------------------------------------------

INSERT INTO compras (recibida, fecha_carga, fecha_recepcion, negocio_id, usuario_id)
SELECT
    true,
    NOW() - (random() * interval '120 days'),
    NOW() - (random() * interval '110 days'),
    n.negocio_id,
    u.usuario_id
FROM generate_series(1, 40)
JOIN negocios n ON n.nombre_negocio = 'Ferretería El Tornillo'
JOIN usuarios u ON u.negocio_id = n.negocio_id AND u.activo = true
ORDER BY random()
LIMIT 40;

INSERT INTO compras (recibida, fecha_carga, fecha_recepcion, negocio_id, usuario_id)
SELECT
    true,
    NOW() - (random() * interval '120 days'),
    NOW() - (random() * interval '110 days'),
    n.negocio_id,
    u.usuario_id
FROM generate_series(1, 25)
JOIN negocios n ON n.nombre_negocio = 'Librería El Saber'
JOIN usuarios u ON u.negocio_id = n.negocio_id AND u.activo = true
ORDER BY random()
LIMIT 25;

-- ------------------------------------------------------------
-- ITEMS COMPRA ADICIONALES
-- ------------------------------------------------------------

INSERT INTO items_compras (cantidad, compra_id, precio_id, producto_id)
SELECT
    (1 + floor(random() * 20))::int,
    c.compra_id,
    pr.precio_id,
    p.producto_id
FROM compras c
JOIN productos p ON p.negocio_id = c.negocio_id
JOIN precios pr ON pr.producto_id = p.producto_id AND pr.tipo = 'COMPRA'
WHERE random() < 0.15;

-- ------------------------------------------------------------
-- VENTAS ADICIONALES
-- ------------------------------------------------------------

INSERT INTO ventas (cliente_id, fecha_hora, forma_id, negocio_id, usuario_id)
SELECT
    c.cliente_id,
    NOW() - (random() * interval '90 days'),
    NULL,
    n.negocio_id,
    u.usuario_id
FROM generate_series(1, 120)
JOIN negocios n ON n.nombre_negocio = 'Ferretería El Tornillo'
JOIN clientes c ON c.negocio_id = n.negocio_id
JOIN usuarios u ON u.negocio_id = n.negocio_id AND u.activo = true
ORDER BY random()
LIMIT 120;

INSERT INTO ventas (cliente_id, fecha_hora, forma_id, negocio_id, usuario_id)
SELECT
    c.cliente_id,
    NOW() - (random() * interval '90 days'),
    NULL,
    n.negocio_id,
    u.usuario_id
FROM generate_series(1, 70)
JOIN negocios n ON n.nombre_negocio = 'Librería El Saber'
JOIN clientes c ON c.negocio_id = n.negocio_id
JOIN usuarios u ON u.negocio_id = n.negocio_id AND u.activo = true
ORDER BY random()
LIMIT 70;

-- ------------------------------------------------------------
-- ITEMS VENTA ADICIONALES
-- ------------------------------------------------------------

INSERT INTO items_ventas (cantidad, precio_id, producto_id, venta_id)
SELECT
    (1 + floor(random() * 5))::int,
    pr.precio_id,
    p.producto_id,
    v.venta_id
FROM ventas v
JOIN productos p ON p.negocio_id = v.negocio_id AND p.activo = true
JOIN precios pr ON pr.producto_id = p.producto_id AND pr.tipo = 'VENTA'
WHERE random() < 0.08;
