-- Esquema inicial

create table categorias (
    activo boolean not null,
    categoria_id bigint generated by default as identity,
    fecha_creacion timestamp(6) not null,
    negocio_id bigint not null,
    descripcion varchar(100) not null,
    primary key (categoria_id),
    unique (descripcion, negocio_id)
);

create table clientes (
    activo boolean not null,
    cliente_id bigint generated by default as identity,
    fecha_creacion timestamp(6) not null,
    negocio_id bigint not null,
    telefono varchar(20),
    nombre_completo varchar(100) not null,
    primary key (cliente_id)
);

create table compras (
    recibida boolean not null,
    compra_id bigint generated by default as identity,
    fecha_carga timestamp(6) not null,
    fecha_recepcion timestamp(6),
    negocio_id bigint not null,
    usuario_id bigint not null,
    primary key (compra_id)
);

create table formas_pago (
    forma_id bigint generated by default as identity,
    descripcion varchar(100) not null unique,
    primary key (forma_id)
);

create table items_compras (
    cantidad integer not null,
    compra_id bigint not null,
    item_compra_id bigint generated by default as identity,
    precio_id bigint not null,
    producto_id bigint not null,
    primary key (item_compra_id)
);

create table items_ventas (
    cantidad integer not null,
    item_venta_id bigint generated by default as identity,
    precio_id bigint not null,
    producto_id bigint not null,
    venta_id bigint not null,
    primary key (item_venta_id)
);

create table negocios (
    activo boolean not null,
    fecha_creacion timestamp(6),
    negocio_id bigint generated by default as identity,
    parametro_id bigint unique,
    nombre_negocio varchar(100) not null unique,
    primary key (negocio_id)
);

create table parametros (
    exigir_forma_de_pago boolean not null,
    una_compra_distintos_proveedores boolean not null,
    parametro_id bigint generated by default as identity,
    primary key (parametro_id)
);

create table precios (
    monto numeric(38,2) not null,
    desde timestamp(6) not null,
    hasta timestamp(6),
    precio_id bigint generated by default as identity,
    producto_id bigint not null,
    tipo varchar(255) not null check ((tipo in ('COMPRA','VENTA'))),
    primary key (precio_id)
);

create table productos (
    activo boolean not null,
    stock integer not null,
    categoria_id bigint,
    fecha_creacion timestamp(6) not null,
    negocio_id bigint not null,
    producto_id bigint generated by default as identity,
    proveedor_id bigint,
    descripcion varchar(100) not null,
    primary key (producto_id),
    unique (descripcion, negocio_id)
);

create table proveedores (
    activo boolean not null,
    negocio_id bigint not null,
    proveedor_id bigint generated by default as identity,
    telefono varchar(20),
    descripcion varchar(100) not null,
    primary key (proveedor_id)
);

create table usuarios (
    activo boolean not null,
    fecha_creacion timestamp(6) not null,
    negocio_id bigint not null,
    ultimo_acceso timestamp(6),
    usuario_id bigint generated by default as identity,
    nombre_completo varchar(100),
    email varchar(255) not null,
    password varchar(255) not null,
    rol varchar(255) not null check ((rol in ('SUPERADMIN','ADMIN','GERENTE','EMPLEADO'))),
    primary key (usuario_id)
);

create table ventas (
    cliente_id bigint not null,
    fecha_hora timestamp(6) not null,
    forma_id bigint,
    negocio_id bigint not null,
    usuario_id bigint not null,
    venta_id bigint generated by default as identity,
    primary key (venta_id)
);

alter table if exists categorias 
    add constraint FK3wmdhk8dknu188g5rugb6rho5 
    foreign key (negocio_id) 
    references negocios;

alter table if exists clientes 
    add constraint FKccuovxxyru49puoyq0hgqb0s5 
    foreign key (negocio_id) 
    references negocios;

alter table if exists compras 
    add constraint FK4lnkw9964v2gf3b2sjbaealqw 
    foreign key (usuario_id) 
    references usuarios;

alter table if exists compras 
    add constraint FKe9smdxck4xoh1v1m0goyw4ssx 
    foreign key (negocio_id) 
    references negocios;

alter table if exists items_compras 
    add constraint FK7p988crripxo0s3lil49h3iqw 
    foreign key (compra_id) 
    references compras;

alter table if exists items_compras 
    add constraint FKtqakqr5qpsi4l38mj1wvscuvw 
    foreign key (precio_id) 
    references precios;

alter table if exists items_compras 
    add constraint FK2i896qk0nuu90kncjd7fagcll 
    foreign key (producto_id) 
    references productos;

alter table if exists items_ventas 
    add constraint FKcokmp28vgx04mhilrbvvpi8vw 
    foreign key (precio_id) 
    references precios;

alter table if exists items_ventas 
    add constraint FKk08c458e2s7spce343h261c1g 
    foreign key (producto_id) 
    references productos;

alter table if exists items_ventas 
    add constraint FKf5m002pvtkrx9skl7emqhkca 
    foreign key (venta_id) 
    references ventas;

alter table if exists negocios 
    add constraint FKcofy3vap8rn38cod9fox97bmc 
    foreign key (parametro_id) 
    references parametros;

alter table if exists precios 
    add constraint FKe1biuxdgj99ycn40dx91xa32v 
    foreign key (producto_id) 
    references productos;

alter table if exists productos 
    add constraint FK2fwq10nwymfv7fumctxt9vpgb 
    foreign key (categoria_id) 
    references categorias;

alter table if exists productos 
    add constraint FKd2djtywmbw974dw5hjrw5ugbh 
    foreign key (negocio_id) 
    references negocios;

alter table if exists productos 
    add constraint FK4s80lxlx2fkci25fcx4r0nbex 
    foreign key (proveedor_id) 
    references proveedores;

alter table if exists proveedores 
    add constraint FK5kiu3tglvogheiidk5ddnupk0 
    foreign key (negocio_id) 
    references negocios;

alter table if exists usuarios 
    add constraint FK4te6rxo55nnja1re00108m8pj 
    foreign key (negocio_id) 
    references negocios;

alter table if exists ventas 
    add constraint FK4dgjhccl2uuo8swmxlxb4ipb5 
    foreign key (cliente_id) 
    references clientes;

alter table if exists ventas 
    add constraint FK3t65vghi4lk9wacxgjg56tjed 
    foreign key (forma_id) 
    references formas_pago;

alter table if exists ventas 
    add constraint FKnvexb891pwiptc9p3534stpml 
    foreign key (negocio_id) 
    references negocios;

alter table if exists ventas 
    add constraint FKco9r9xjcdqtgd4nvnnolsr6ei 
    foreign key (usuario_id) 
    references usuarios;